[project]
name = "test-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pandas>=2.0.0",
    "xlrd>=2.0.0",
    "openpyxl>=3.0.0",
    "pandas-stubs>=2.0.0",
]

[tool.pyright]
reportMissingTypeStubs = false
